### ISSUE TITLE
SDLE default location is eastern Australia

### ISSUE THREAD

**Issue by EzraKuhr** [bmlt-enabled/sdle#18]
SDLE already has access to my location on chrome79 on win10. When it opens it should display the map for my current location instead of Australia. Also a nice feature would be a 'return to current location' button. 

`sdle.js?v=11:135 Uncaught TypeError: Cannot read property 'parent_id' of undefined
    at sdle.js?v=11:135
    at Object.success (sdle.js?v=11:60)
    at u (jquery-3.3.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.3.1.min.js:2)
    at k (jquery-3.3.1.min.js:2)
    at HTMLScriptElement.n (jquery-3.3.1.min.js:2)
    at HTMLScriptElement.dispatch (jquery-3.3.1.min.js:2)
    at HTMLScriptElement.y.handle (jquery-3.3.1.min.js:2)`

**Comment by EzraKuhr** [comment]
Steps to reproduce: visit SDLE. Defaulted to Australia. Allowed location access. Relaunched and it still defaulted there.

**Comment by EzraKuhr** [comment]
It did resolve properly in the same session that i allow location access, but subsequent reloads with the permission already allowed fail with the above JS error

**Comment by radius314** [comment]
Unable to repro.

**Comment by EzraKuhr** [comment]
I still experience this issue. I visit sdle, allow location permission and it changes to florida. on a page refresh, it reverts back to Australia. On a new tab it goes to australia. cookies and location are allowed. 
![image](https://user-images.githubusercontent.com/20930402/73370089-a97d5880-4281-11ea-865f-83f1f294595e.png)

**Comment by radius314** [comment]
This means that your system is for some reason unable to access location.
It’s not a bug with the application.

**Comment by EzraKuhr** [comment]
I dont have location permission issues on any other page that uses that, including several BMLT Satellite/Crouton Companion maps. And it goes to Florida when I initially give it permission.
