### ISSUE TITLE
Feature request for Regional data

### ISSUE THREAD

**Issue by EzraKuhr** [bmlt-enabled/sdle#2]
Itd be great if sdle could return regional info ie what region, website, (and phoneline if available)

**Comment by radius314** [comment]
This feature would have to assume that one level up is the region then.  This may not always be the case.  For instance Georgia Areas are part of a metro, which is the parent.  The region would be two levels up.  

Another way to approach this is to recurse the service body hierarchy until parent = 0 / NULL, and show / visual those service bodies beneath this one.

**Comment by radius314** [comment]
Another way to approach this feature is to highlight the boundaries of the service body selected when it’s found.  From there you could have a click through the next service body beneath it (parent).  That then gives focus away from the result to this new result, that also shows all the boundaries.

**Comment by EzraKuhr** [comment]
I think the full hierarchy would work best.

I think this is an important feature. Take Central Area in San Diego. Sdle returns a dead website, and theres no helpline, but i know their parent, San Diego Imperial Counties region has a regional website with a page for the area and a regional helpline that covers all the areas.

**Comment by EzraKuhr** [comment]
I well aware of both those points. And I know the data is only as reliable as the data entered by the service body, but showing region/parent info still presents more info when the area info is bad/absent/not helpful.

**Comment by radius314** [comment]
Added the parent service body in parenthesis.

![image](https://user-images.githubusercontent.com/1850811/58384619-a83cb300-7fb1-11e9-8c0a-308b9974a8f4.png)

**Comment by radius314** [comment]
Marking this completed.
