### ISSUE TITLE
feature request - add meeting that doesn't meet weekly

### ISSUE THREAD

**Issue by lucy12187** [bmlt-enabled/sdle#20]
**oops i added this in the wrong place... doesn't look like i can delete it. i'll repost in the correct place.**
I had a request to add a meeting that meets monthly.  its not a service meeting.
Not sure its possible or even worth it to make an option to add meetings monthly, 1st and 3rd week, 2nd and 4th week, every other week, etc... i'm sure it wouldn't be used much. but just thought i'd ask!

**Comment by dgershman** [comment]
Ok you can open this under [bmlt-enabled/bmlt](https://github.com/bmlt-enabled/bmlt-root-server)
