### ISSUE TITLE
Location showing no BMLT, when there is

### ISSUE THREAD

**Issue by dgershman** [bmlt-enabled/sdle#50]
I noticed today that when you hit the page, it returns this.  I haven't tried on a non mobile device.  There is definitely a root server or two nearby this query.

Separately I noticed that the search box is cutoff.

![image](https://github.com/user-attachments/assets/cd11850b-dcbf-4898-9379-820a09ed183c)

**Comment by dgershman** [comment]
@pjaudiomv

**Comment by pjaudiomv** [comment]
Did you have location sharing off maybe? I'll
Try and reproduce

**Comment by pjaudiomv** [comment]
Ok ya weird able to repro, it seems to happen if you refresh page or if you got back to it after initial load. I fixed search box being cut off and gonna work on fix for this

**Comment by pjaudiomv** [comment]
word should be fixed, could only get it to happen in safari on ios but timing issue in loading of service body data

**Comment by dgershman** [comment]
Cool looks good now

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
